version: '3'
services:
  pku-dair-backend:
    build: .
    ports:
      - "60031:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - /root/docker/apps/pku_dair_be/db:/app/db
      - /root/docker/apps/pku_dair_be/member_cv:/app/member_cv
      - /root/docker/apps/pku_dair_be/news:/app/news
      - /root/docker/apps/pku_dair_be/user:/app/user
    restart: always